import { useState, useEffect } from 'react';
import { Link } from 'react-router-dom';
import { api } from '../../utils/api';
import { useAuth } from '../../context/AuthContext';
import { useNotifications } from '../../context/NotificationContext';

export default function Reports() {
  const [reports, setReports] = useState([]);
  const [loading, setLoading] = useState(true);
  const { user } = useAuth();
  const { addToast } = useNotifications();

  useEffect(() => {
    api.get('/reports').then(d => setReports(d.reports)).catch(() => {}).finally(() => setLoading(false));
  }, []);

  const handleDelete = async (id) => {
    if (!confirm('Delete this report?')) return;
    try {
      await api.delete(`/reports/${id}`);
      setReports(prev => prev.filter(r => r.id !== id));
      addToast('Report deleted', 'success');
    } catch (err) { addToast(err.message, 'error'); }
  };

  const handleDownload = (report) => {
    const content = JSON.parse(report.content || '{}');
    const blob = new Blob([JSON.stringify(content, null, 2)], { type: 'application/json' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `${report.title.replace(/[^a-z0-9]/gi, '_')}.json`;
    a.click();
    URL.revokeObjectURL(url);
  };

  const typeColors = { full: 'var(--accent-primary)', executive: 'var(--accent-purple)', technical: 'var(--accent-green)', vulnerability: 'var(--accent-yellow)' };

  return (
    <div>
      <div className="page-header"><h1>Reports ({reports.length})</h1></div>

      {loading ? <div className="loading-page"><div className="spinner" /></div> : reports.length === 0 ? (
        <div className="empty-state"><div className="icon">📄</div><h3>No reports generated yet</h3><p>Generate reports from engagement pages</p></div>
      ) : (
        <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fill, minmax(350px, 1fr))', gap: '1rem' }}>
          {reports.map(r => (
            <div key={r.id} className="card" style={{ display: 'flex', flexDirection: 'column', gap: '0.75rem' }}>
              <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'flex-start' }}>
                <div>
                  <h3 style={{ fontSize: '1rem', fontWeight: 600 }}>{r.title}</h3>
                  <p style={{ fontSize: '0.8rem', color: 'var(--text-muted)' }}>
                    <Link to={`/engagements/${r.engagement_id}`}>{r.engagement_name}</Link>
                  </p>
                </div>
                <span style={{ padding: '0.2rem 0.6rem', borderRadius: '9999px', fontSize: '0.7rem', fontWeight: 600, background: `${typeColors[r.report_type] || '#6b7280'}20`, color: typeColors[r.report_type] || '#6b7280', textTransform: 'capitalize' }}>
                  {r.report_type}
                </span>
              </div>
              <div style={{ fontSize: '0.8rem', color: 'var(--text-secondary)' }}>
                Generated by {r.generated_by_name} &middot; {new Date(r.generated_at).toLocaleDateString()}
              </div>
              <div style={{ display: 'flex', gap: '0.5rem', marginTop: 'auto' }}>
                <button className="btn btn-primary btn-sm" onClick={() => handleDownload(r)}>Download JSON</button>
                {(user?.role === 'admin' || user?.role === 'manager') && (
                  <button className="btn btn-danger btn-sm" onClick={() => handleDelete(r.id)}>Delete</button>
                )}
              </div>
            </div>
          ))}
        </div>
      )}
    </div>
  );
}
